-- Reference SQL schema for the conversation thematic analysis application.
-- Runtime schema is created by SQLAlchemy models in app/db/models.py.
CREATE TABLE conversations (id INTEGER PRIMARY KEY, external_id TEXT, title TEXT, source TEXT, metadata_json TEXT, created_at DATETIME);
CREATE TABLE speakers (id INTEGER PRIMARY KEY, conversation_id INTEGER NOT NULL, speaker_label TEXT NOT NULL, role TEXT, metadata_json TEXT, FOREIGN KEY(conversation_id) REFERENCES conversations(id));
CREATE TABLE turns (id INTEGER PRIMARY KEY, conversation_id INTEGER NOT NULL, speaker_id INTEGER, turn_index INTEGER NOT NULL, text TEXT NOT NULL, timestamp TEXT, metadata_json TEXT, FOREIGN KEY(conversation_id) REFERENCES conversations(id), FOREIGN KEY(speaker_id) REFERENCES speakers(id));
CREATE TABLE segments (id INTEGER PRIMARY KEY, turn_id INTEGER NOT NULL, segment_index INTEGER NOT NULL, text TEXT NOT NULL, segmentation_strategy TEXT NOT NULL, original_text TEXT NOT NULL, metadata_json TEXT, FOREIGN KEY(turn_id) REFERENCES turns(id));
CREATE TABLE codebook_versions (id INTEGER PRIMARY KEY, name TEXT NOT NULL, version TEXT NOT NULL, description TEXT, theoretical_framework TEXT, created_at DATETIME, is_active BOOLEAN);
CREATE TABLE framework_settings (id INTEGER PRIMARY KEY, codebook_version_id INTEGER NOT NULL, primary_framework TEXT NOT NULL, supporting_frameworks_json TEXT, analysis_orientation TEXT, coding_orientation TEXT, theme_orientation TEXT, epistemological_position TEXT, semantic_or_latent TEXT, inductive_or_deductive TEXT, description TEXT, FOREIGN KEY(codebook_version_id) REFERENCES codebook_versions(id));
CREATE TABLE methodological_phases (id INTEGER PRIMARY KEY, analysis_run_id INTEGER NOT NULL, phase_number INTEGER NOT NULL, phase_name TEXT NOT NULL, framework_reference TEXT NOT NULL, status TEXT, started_at DATETIME, completed_at DATETIME, notes TEXT, FOREIGN KEY(analysis_run_id) REFERENCES analysis_runs(id));
CREATE TABLE themes (id INTEGER PRIMARY KEY, codebook_version_id INTEGER NOT NULL, name TEXT NOT NULL, description TEXT, analytical_definition TEXT, inclusion_criteria TEXT, exclusion_criteria TEXT, examples_json TEXT, counterexamples_json TEXT, parent_theme_id INTEGER, status TEXT, FOREIGN KEY(codebook_version_id) REFERENCES codebook_versions(id));
CREATE TABLE candidate_themes (id INTEGER PRIMARY KEY, analysis_run_id INTEGER NOT NULL, name TEXT NOT NULL, description TEXT, supporting_codes_json TEXT, supporting_segments_json TEXT, review_status TEXT, rationale TEXT, FOREIGN KEY(analysis_run_id) REFERENCES analysis_runs(id));
CREATE TABLE codes (id INTEGER PRIMARY KEY, theme_id INTEGER NOT NULL, name TEXT NOT NULL, description TEXT, analytical_definition TEXT, inclusion_criteria TEXT, exclusion_criteria TEXT, indicators_json TEXT, examples_json TEXT, counterexamples_json TEXT, FOREIGN KEY(theme_id) REFERENCES themes(id));
CREATE TABLE coding_features (id INTEGER PRIMARY KEY, codebook_version_id INTEGER NOT NULL, name TEXT NOT NULL, description TEXT, feature_type TEXT NOT NULL, allowed_values_json TEXT, extraction_hint TEXT, is_required BOOLEAN, FOREIGN KEY(codebook_version_id) REFERENCES codebook_versions(id));
CREATE TABLE coders (id INTEGER PRIMARY KEY, name TEXT UNIQUE NOT NULL, metadata_json TEXT);
CREATE TABLE annotations (id INTEGER PRIMARY KEY, segment_id INTEGER NOT NULL, code_id INTEGER NOT NULL, coder_id INTEGER NOT NULL, analysis_run_id INTEGER NOT NULL, confidence REAL, rationale TEXT, evidence_text TEXT, created_at DATETIME, FOREIGN KEY(segment_id) REFERENCES segments(id), FOREIGN KEY(code_id) REFERENCES codes(id), FOREIGN KEY(coder_id) REFERENCES coders(id), FOREIGN KEY(analysis_run_id) REFERENCES analysis_runs(id));
CREATE TABLE coding_decisions (id INTEGER PRIMARY KEY, annotation_id INTEGER NOT NULL, decision_type TEXT NOT NULL, decision_note TEXT, framework_phase TEXT, created_at DATETIME, FOREIGN KEY(annotation_id) REFERENCES annotations(id));
CREATE TABLE memos (id INTEGER PRIMARY KEY, conversation_id INTEGER, segment_id INTEGER, coder_id INTEGER, memo_type TEXT NOT NULL, text TEXT NOT NULL, related_phase TEXT, created_at DATETIME);
CREATE TABLE reflexive_journal_entries (id INTEGER PRIMARY KEY, analysis_run_id INTEGER, coder_id INTEGER, text TEXT NOT NULL, related_phase TEXT, created_at DATETIME);
CREATE TABLE audit_trail_entries (id INTEGER PRIMARY KEY, analysis_run_id INTEGER, phase_number INTEGER, action_type TEXT NOT NULL, description TEXT NOT NULL, before_state_json TEXT, after_state_json TEXT, created_at DATETIME);
CREATE TABLE adjudication_records (id INTEGER PRIMARY KEY, analysis_run_id INTEGER NOT NULL, segment_id INTEGER NOT NULL, code_id INTEGER, decision TEXT NOT NULL, rationale TEXT, created_at DATETIME);
CREATE TABLE analysis_runs (id INTEGER PRIMARY KEY, codebook_version_id INTEGER NOT NULL, run_name TEXT NOT NULL, run_type TEXT, config_json TEXT, created_at DATETIME, FOREIGN KEY(codebook_version_id) REFERENCES codebook_versions(id));
CREATE TABLE exports (id INTEGER PRIMARY KEY, analysis_run_id INTEGER NOT NULL, export_format TEXT NOT NULL, path TEXT NOT NULL, created_at DATETIME, FOREIGN KEY(analysis_run_id) REFERENCES analysis_runs(id));
